#!/bin/bash
#PBS -A lp_stadius_fpga_ai
#PBS -l nodes=1:ppn=36:gpus=4:skylake
#PBS -l partition=gpu
#PBS -l pmem=5gb
#PBS -o debug/$PBS_JOBNAME.out
#PBS -e debug/$PBS_JOBNAME.err
#PBS -m bae
#PBS -M maxim.yudayev@kuleuven.be

# (1/20) Full Skylake x4 P100 GPU node (requires 9 cores per gpu)
# GPU partition
# Skylake GPU nodes have thin node's memory (192GB)

mail -s "[$PBS_JOBNAME]: STARTED" maxim.yudayev@kuleuven.be <<< ""

# Change directory to location from which task was submitted to queue: $VSC_DATA/...
cd $PBS_O_WORKDIR
# Purge all existing software packages
module purge

# Load environment
source activate rt-st-gcn

(>&1 echo "$@")
(>&1 echo 'starting computation')
# Execute and time the script
time python ../main.py test "$@"
